basic.showNumber(1)
basic.showNumber(2)
basic.showNumber(3)
basic.pause(1000)
basic.showArrow(ArrowNames.East)
basic.showArrow(ArrowNames.West)
basic.showArrow(ArrowNames.South)
basic.showArrow(ArrowNames.North)
basic.pause(1000)
basic.showString("Hello! Microbit!")
basic.showIcon(IconNames.Happy)
soundExpression.giggle.playUntilDone()
basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.SmallHeart)
})
